### PR TITLE
Vanilla java vs android separation

### PR DESCRIPTION
**Pull request by Blahartinger**
Refactoring the project to make kin-sdk and kin-base pure vanilla java/kotlin.

A new module, kin-android, now contains all android platform specific code.

Clients who use this sdk for android should only pull in kin-android module.
Clients looking for a java only implementation should only include kin-sdk.

Summary of modifications:
- changed nullability annotations from support lib version to jsr305
compliant variant
- changed android platform URI to vanilla java.net.URI
- modified KinClient interface to accommodate removal of Context
(only storage to shared prefs required it) and addition of main thread
handler
- injected storage via new KinStorageFactory interface (see
KinStorageFactoryImpl for android sharedPrefs impl)
- copied kin-utils lib temporarily locally in kin-sdk and made it
vanilla java/kotlin (TODO: another PR will follow with that change)
- kin-utils copy now takes in a MainHandler who's responsibility is to post
Runnables to the main thread.
- Also created AndroidKinClient to conform to previous Context aware interface  …
of KinClient. Also refactored KinClient -> KinClientImpl and created interface.

All Tests including integration pass.

### CODE REVIEW

**Comment by Blahartinger** [comment]
Any thoughts on this?

**Comment by yosriz** [comment]
@Blahartinger what's your use case for this separation?

**Comment by mrsegev** [comment]
Hi @Blahartinger, can you please specify what problem are we solving by adopting this separation?

**Comment by Blahartinger** [comment]
The primary purpose for proposing this change is to provide a better separation of concerns in a mobile android application using the sdk. In my case, that's Kik Messenger.

We have different modules for our services layer than we do for any UI or platform specific code so it would break that separation by having a single kin module that both controls the service layer and is contaminated with android platform source.

Since there were very few android platform specific references in your sdk, as I listed above in what I changed, this allows for your two modules to remain vanilla java, while providing injectable platform specific behaviour through the new interfaces provided. 

Additionally, benefits would include:
- allowing and promoting to other kin devs to maintain the same clean arch separation of concerns within their own app
- speeding up and simplifying all of your unit tests since they no longer require roboelectric and are pure JUnit
- you won't have to update or retarget your base modules when Android OS versions change since java 7 and 8 new development is over (we're at Java 10 now but Android is stuck in the past here for now)
- the ability for this java base sdk to be used on a Java server 
- the ability to use it in a java desktop client

**Comment by yosriz** [comment]
@Blahartinger can you elaborate on the benefits for an app? I don't really get it, how come the internal of the structure of the SDK will benefit a consumer of the SDK in an app?
eventually, you'll need to use the android part, and in tests you'll need to mock this module whether you need context for instantiating it or not, kin-sdk is an external dependency for your app and like any external dependency, you'll need to mock it functionality under test, not because the android part, but because of network i.e. communication with external service which is the blockchain.
I don't see how having only java part, i.e. `KinClientImpl` will give a host app any benefit for testing.
Regarding the separation of concerns, that again I think, not a concern for the host app,  we would like to provide a module that's both responsible for storing an account, and accessing the blockchain service.
What do I miss here?
As for the other benefits:
* Internally, we have good separation, so we had like 85% coverage with unit tests only.
* Java Server SDK will need different APIs, and should follow our python and node (in the making) functionality which are different, that requires additional effort in order to share code between the client and server sdks.
* Android is in our main focus, at least for now, so we will maintain Android OS changes anyway, and in any case, we must aim for the lowest common denominator, so I don't understand the benefit here.

**Comment by Blahartinger** [comment]
Developers gain the option to only pull in **kin-sdk** and it's dependency kin-base to java only modules of their applications. This is impossible today. 

For example...
Given a simple app structure with two modules:

- App (UI, business logic, navigation, this is your Android app)
- Core (the guts of your services, storage, etc)

If my Core module contains all my services, and very likely there is no need for Android platform components I would definitely want to keep it java only. This gives me a variety of other benefits (see below*), some of which I've touched upon earlier. If this module wants to interact with the Kin SDK it cannot because it would need to become an Android library - this is undesirable. 

So....

With the new separation, I can have Core module depend on **kin-sdk** and transitively **kin-base**.
And my App module would depend on **kin-android**.

This allows me to inject the Andorid platform-specific component implementations provided in **kin-android** at instantiation time of the KinClientImpl in the App module. In common practice, this is typically done via Dagger or Guice dependency injection libraries - though fundamentally __no t__ required to achieve this.

With these changes, you still retain an Android SDK under the **kin-android** module by pulling it indirectly instead of the whole top level project. 

If developers just want to continue to pull in one massive dependency into a single module application they absolutely still can by depending on **kin-android**
e.g. implementation("com.github.Blahartinger.kin-sdk-android:kin-sdk:5ff849021f")

In summary, nobody has to change their app if they don't want to, this just provides additional options for developers in the Kin Ecosystem while making a very tiny change to the constructor of one component. A net gain without pain, a highly desirable outcome if we work together.


* Clarification of benefits of accepting this separation include:
- more options for the ecosystem of Kin developers to structure their code -> resulting in fewer forks that developers like myself will make anyway
- following an important clean architecture principle by making your code as framework independent [Android frameworks] as possible. A not so rare case of when you can you should. The code as-is, does follow other principles such as independent UI (there is none!), it's pretty testable, and in some cases independent of external agency (the idea that business logic shouldn't know anything about the outside world)
-This change also provides independent storage, another important clean arch principle, developers can choose how they want to implement storage for wallet keys - an protect their access further if they should choose. I think for storage this should be pushed further on other PRs to allow for implementations of all storage elements. It's abnormal to have a library dictate storage elements without providing its parent app with at least a handle to them.  
-  faster build times (with tests) -> translating into faster development especially as the project grows
- multi-platform support -> whether you want to endorse it or not, this absolutely could be used on a server this way
- no android platform upkeep -> when android APIs change, you won't have to! and if you do - it'll be all in a few classes in a separate module -> **kin-android**
- there are lots more...

On Testing...
JUnitTestRunner is verifiably faster than running the RoboelectricTestRunner; approximately 4x faster. This is especially important as your project grows larger and rely on continuous integration builds that can take a long time to run...or just normal developer workstation development of new features.  
An example of validating this is here: https://medium.com/@fmedlin/how-fast-are-android-unit-tests-5c52ef84e52e

**Comment by Blahartinger** [comment]
Replacing this with https://github.com/kinecosystem/kin-sdk-android/pull/51

**Pull request closed without merging**
